version: '3.3'
services:
  db_uaa:
    image: mysql:5.7
    restart: always
    container_name: db_uaa
    environment:
      MYSQL_DATABASE: 'uaa'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'cuongnm'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'cuongnm'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'cuongnm'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3307'
      # Where our data will be persisted
    volumes:
      - ./sql-scripts/uaa.sql:/docker-entrypoint-initdb.d/uaa.sql
# Names our volume
volumes:
  my-db: